{
  "hash": "b97ac3725c3a3c2cbf5b32001e2095e3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Deskriptives\"\nexecute:\n  echo: false\n  warning: false\nfrom: markdown+emoji\n---\n\n\n\n\n# Deutschlandweiter Überblick\n\n\n::: {.cell}\n\n:::\n\n\n::: {.callout-note collapse=\"true\"}\n## Datenquellen\n\n**Anzahl Ortsgruppen**\n\n- 40 Anzahl von Antworten auf den [Ortsgruppen Fragebogen](https://ee-eu.kobotoolbox.org/single/cs5DElJT)\n- 40 Anzahl verschiedener Werte bei den Antworten zur Frage \"*Wie heißt deine Ortsgruppe?*\" im [Teilnehmer*innen Fragebogen](https://ee-eu.kobotoolbox.org/single/UgaA9dLH)\n\n**Anzahl Aktive**\n\n| Fragebogen                 | Teilnehmer\\*innen | Leitung und Mitarbeitende | Insgesamt                                 |\n|-----------------|-----------------|-----------------|----------------------|\n| [Teilnehmer*innen Fragebogen](https://ee-eu.kobotoolbox.org/single/UgaA9dLH) | 287[^1]   | *nicht abgefragt*         | *nicht errechenbar*                       |\n| [Ortsgruppen Fragebogen](https://ee-eu.kobotoolbox.org/single/cs5DElJT) | 484       | 199          | 683 |\n\n: Anzahl Aktive {#tbl-summary}\n:::\n\n[^1]: Anzahl der Antworten auf den [Teilnehmer*innen Fragebogen](https://ee-eu.kobotoolbox.org/single/UgaA9dLH)\n\n\nEs gibt **zwischen 30 und 40 Ortsgruppen.**\n\nInsgesamt sind in den Ortsgruppen von TEN SING **683 Personen aktiv**.\n\nDavon sind **zwischen 287 und 484 als Teilnehmer\\*innen** engagiert.  **199** Personen **arbeiten** für TEN SING oder engagieren sich **in der Leitung** einer Ortsgruppe.\n\n## Ortsgruppengröße\n\n::: panel-tabset\n## Alle\n\nHier wird die Anzahl aller Aktiven betrachtet. Diese ist definiert als **Summe von Teilnehmer\\*innen und Leitung und Mitarbeitenden**.\n\nIm Durchschnitt hat eine TenSing-Ortsgruppe 23 Aktive. Dabei ist die Spannbreite recht groß. Die kleinste Ortsgruppe hat 9 Aktive, die größte widerrum 48 Aktive.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](deskriptiv_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n## Teilnehmer\\*innen\n\nHier wird die Anzahl der **Teilnehmer\\*innen** betrachtet: Im Durchschnitt hat eine TenSing-Ortsgruppe 16 Teilnehmer\\*innen (TN). Dabei ist die Spannbreite recht groß. Die kleinste Ortsgruppe hat 6 TN, die größte widerrum 34 TN.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](deskriptiv_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n## Mitarbeitende / Leitung\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](deskriptiv_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Interpretationshilfe\n\nDie Grafik zeigt auf der waagerechten Achse die Gruppengröße und auf der senkrechten Achse, wie viele Gruppen diese Gruppengröße haben. Die gestrichelte Linie zeigt die mittlere Gruppengröße an (Mittelwert).\n:::\n\n## Geschlecht\n\n::: panel-tabset\n## Alle\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](deskriptiv_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n## Mitarbeitende (inkl. Leitung)\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](deskriptiv_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n## Teilnehmende\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](deskriptiv_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n:::\n\n## Alter\n\n::: panel-tabset\n## Alle\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](deskriptiv_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n## Mitarbeitende (inkl. Leitung)\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](deskriptiv_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n## Teilnehmende\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](deskriptiv_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n:::\n\n\n## Aktivitäten\n\n### Wie viel Zeit verbringen Jugendliche mit TEN SING?\n**TODO**\n\n### Wann finden TEN SING Veranstaltungen statt? An welchen Tagen?\n\n\n::: {.cell}\n\n:::\n\n\n\n### Wie viele Stunden in der Woche finden TEN SING Veranstaltungen statt? \n\nDie TEN SING Gruppen verbringen **jede Woche zusammen insgesamt 85 Stunden** mit ihren Treffen. \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](deskriptiv_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n### Wie lange dauert ein TEN SING Treffen?\nTEN SING Treffen dauern im Durchschnitt 2.2972973 Stunden.\n\n### Wie viele Auftritte finden pro Schuljahr statt?\n\nIm letzten Schuljahr fanden insgesamt 97 statt. \n\n\n### Welche Angebote finden statt? \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](deskriptiv_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n###  Zufriedenheit mit TENSING (Weiterempfehlungsfrage)\n**TODO**\n\n# Regionen und Ortsgruppen\n\n::: {.callout-note collapse=\"true\"}\n## Datenquelle\n\n\n\nRelevante Fragen:\n\n- **Frage** \"*In welcher Region liegt deine Ortsgruppe?*\" im [Ortsgruppen Fragebogen](https://ee-eu.kobotoolbox.org/single/cs5DElJT)\n- **Frage** \"*Wie heißt deine Ortsgruppe?*\" im [Ortsgruppen Fragebogen](https://ee-eu.kobotoolbox.org/single/cs5DElJT)\n- **Frage** \"*Wie heißt deine Ortsgruppe?*\" im [Teilnehmer*innen Fragebogen](https://ee-eu.kobotoolbox.org/single/UgaA9dLH) \n\n\nOrtsgruppen, die von Teilnehmenden genannt werden, bekommen das Label \"TN\" in der Spalte `Datenquelle`. Ortsgruppen, für die der Ortsgruppen-Fragebogen ausgefüllt wurde, bekommen das Label \"OG\" in der Spalte `Datenquelle`. \nBeachte: Manche Ortsgruppen kommen nur im TN-Fragebogen vor, da die Ortsgruppenleitung den OG-Fragebogen nicht beantwortet hat\n\n:::\n\n::: callout-tip\nMit einem Klick auf den :arrow_forward: kannst du jede Region öffnen und eine Liste ihrer Ortsgruppen sehen.\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"reactable html-widget html-fill-item\" id=\"htmlwidget-10d1c88453f3e11e2964\" style=\"width:auto;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-10d1c88453f3e11e2964\">{\"x\":{\"tag\":{\"name\":\"Reactable\",\"attribs\":{\"data\":{\"Region\":[\"Ostwestfalen-Lippe\",\"Nord\",\"Sachsen\",\"Thüringen\",\"Bergischland-Ruhrgebiet (BLRG)\",\"Niederrhein\",\"Ostwerk\",\"Hessen\",\"Süden\"],\"Anzahl Ortsgruppen\":[8,7,5,5,4,4,4,3,2]},\"columns\":[{\"id\":\".details\",\"name\":\"\",\"type\":null,\"sortable\":false,\"resizable\":false,\"filterable\":false,\"searchable\":false,\"width\":45,\"align\":\"center\",\"details\":[{\"name\":\"div\",\"attribs\":{\"style\":{\"padding\":\"1rem\"}},\"children\":[{\"name\":\"Reactable\",\"attribs\":{\"data\":{\"Ortsgruppe\":[\"Gütersloh\",\"Knetterheide\",\"Lübbecke\",\"Münster\",\"Rheda-Wiedenbrück\",\"Versmold\",\"Brackwede-Quelle\",\"Löhne\"],\"Datenquelle\":[\"OG-FB, TN-FB\",\"OG-FB, TN-FB\",\"OG-FB, TN-FB\",\"OG-FB, TN-FB\",\"OG-FB, TN-FB\",\"OG-FB, TN-FB\",\"TN-FB\",\"TN-FB\"]},\"columns\":[{\"id\":\"Ortsgruppe\",\"name\":\"Ortsgruppe\",\"type\":\"character\"},{\"id\":\"Datenquelle\",\"name\":\"Datenquelle\",\"type\":\"character\"}],\"outlined\":true,\"dataKey\":\"86f4e61ab727dbddfd6880e5cc3ee306\",\"static\":false,\"nested\":true},\"children\":[]}]},{\"name\":\"div\",\"attribs\":{\"style\":{\"padding\":\"1rem\"}},\"children\":[{\"name\":\"Reactable\",\"attribs\":{\"data\":{\"Ortsgruppe\":[\"Augustfehn-Apen\",\"Bremen\",\"Moormerland\",\"Oldenburg\",\"Sittensen\",\"Ostrhauderfehn\",\"Hambergen\"],\"Datenquelle\":[\"OG-FB, TN-FB\",\"OG-FB, TN-FB\",\"OG-FB, TN-FB\",\"OG-FB, TN-FB\",\"TN-FB\",\"TN-FB\",\"TN-FB\"]},\"columns\":[{\"id\":\"Ortsgruppe\",\"name\":\"Ortsgruppe\",\"type\":\"character\"},{\"id\":\"Datenquelle\",\"name\":\"Datenquelle\",\"type\":\"character\"}],\"outlined\":true,\"dataKey\":\"435deb0166f41acf82fb96168554d698\",\"static\":false,\"nested\":true},\"children\":[]}]},{\"name\":\"div\",\"attribs\":{\"style\":{\"padding\":\"1rem\"}},\"children\":[{\"name\":\"Reactable\",\"attribs\":{\"data\":{\"Ortsgruppe\":[\"Dresden\",\"Pirna\",\"Zittau\",\"Coswig\",\"Zwickau\"],\"Datenquelle\":[\"OG-FB, TN-FB\",\"OG-FB, TN-FB\",\"OG-FB\",\"TN-FB\",\"TN-FB\"]},\"columns\":[{\"id\":\"Ortsgruppe\",\"name\":\"Ortsgruppe\",\"type\":\"character\"},{\"id\":\"Datenquelle\",\"name\":\"Datenquelle\",\"type\":\"character\"}],\"outlined\":true,\"dataKey\":\"f98fc0f6e1a4b8e4b17ea6f24a80e8b9\",\"static\":false,\"nested\":true},\"children\":[]}]},{\"name\":\"div\",\"attribs\":{\"style\":{\"padding\":\"1rem\"}},\"children\":[{\"name\":\"Reactable\",\"attribs\":{\"data\":{\"Ortsgruppe\":[\"Erfurt\",\"Rudolstadt\",\"Sonneberg\",\"Weimar\",\"Zeulenroda\"],\"Datenquelle\":[\"OG-FB, TN-FB\",\"OG-FB, TN-FB\",\"OG-FB, TN-FB\",\"OG-FB, TN-FB\",\"OG-FB, TN-FB\"]},\"columns\":[{\"id\":\"Ortsgruppe\",\"name\":\"Ortsgruppe\",\"type\":\"character\"},{\"id\":\"Datenquelle\",\"name\":\"Datenquelle\",\"type\":\"character\"}],\"outlined\":true,\"dataKey\":\"4609437cc25a8ed84ced6e8909d29ba2\",\"static\":false,\"nested\":true},\"children\":[]}]},{\"name\":\"div\",\"attribs\":{\"style\":{\"padding\":\"1rem\"}},\"children\":[{\"name\":\"Reactable\",\"attribs\":{\"data\":{\"Ortsgruppe\":[\"Burgaltendorf\",\"Haßlinghausen\",\"Hagen\",\"Bochum\"],\"Datenquelle\":[\"OG-FB, TN-FB\",\"OG-FB, TN-FB\",\"TN-FB\",\"TN-FB\"]},\"columns\":[{\"id\":\"Ortsgruppe\",\"name\":\"Ortsgruppe\",\"type\":\"character\"},{\"id\":\"Datenquelle\",\"name\":\"Datenquelle\",\"type\":\"character\"}],\"outlined\":true,\"dataKey\":\"625b1a84556d5c99ed68fb3bfd24f660\",\"static\":false,\"nested\":true},\"children\":[]}]},{\"name\":\"div\",\"attribs\":{\"style\":{\"padding\":\"1rem\"}},\"children\":[{\"name\":\"Reactable\",\"attribs\":{\"data\":{\"Ortsgruppe\":[\"Borken\",\"Moers\",\"Solingen\",\"Duisburg\"],\"Datenquelle\":[\"OG-FB, TN-FB\",\"OG-FB, TN-FB\",\"OG-FB, TN-FB\",\"TN-FB\"]},\"columns\":[{\"id\":\"Ortsgruppe\",\"name\":\"Ortsgruppe\",\"type\":\"character\"},{\"id\":\"Datenquelle\",\"name\":\"Datenquelle\",\"type\":\"character\"}],\"outlined\":true,\"dataKey\":\"14f3e44424b8deac81d7670cd90bc50a\",\"static\":false,\"nested\":true},\"children\":[]}]},{\"name\":\"div\",\"attribs\":{\"style\":{\"padding\":\"1rem\"}},\"children\":[{\"name\":\"Reactable\",\"attribs\":{\"data\":{\"Ortsgruppe\":[\"2.0\",\"Brandenburg\",\"Frankfurt (Oder)\",\"Zeuthen\"],\"Datenquelle\":[\"OG-FB, TN-FB\",\"OG-FB\",\"OG-FB, TN-FB\",\"OG-FB, TN-FB\"]},\"columns\":[{\"id\":\"Ortsgruppe\",\"name\":\"Ortsgruppe\",\"type\":\"character\"},{\"id\":\"Datenquelle\",\"name\":\"Datenquelle\",\"type\":\"character\"}],\"outlined\":true,\"dataKey\":\"8d59adc213d3e1c460fe5752709ed3d1\",\"static\":false,\"nested\":true},\"children\":[]}]},{\"name\":\"div\",\"attribs\":{\"style\":{\"padding\":\"1rem\"}},\"children\":[{\"name\":\"Reactable\",\"attribs\":{\"data\":{\"Ortsgruppe\":[\"Eschwege\",\"Homberg (Efze)\",\"Ehringen\"],\"Datenquelle\":[\"OG-FB, TN-FB\",\"OG-FB, TN-FB\",\"TN-FB\"]},\"columns\":[{\"id\":\"Ortsgruppe\",\"name\":\"Ortsgruppe\",\"type\":\"character\"},{\"id\":\"Datenquelle\",\"name\":\"Datenquelle\",\"type\":\"character\"}],\"outlined\":true,\"dataKey\":\"8eddf1cf30022acef974a207afbf0b10\",\"static\":false,\"nested\":true},\"children\":[]}]},{\"name\":\"div\",\"attribs\":{\"style\":{\"padding\":\"1rem\"}},\"children\":[{\"name\":\"Reactable\",\"attribs\":{\"data\":{\"Ortsgruppe\":[\"Ulm\",\"Untermünkheim\"],\"Datenquelle\":[\"OG-FB\",\"TN-FB\"]},\"columns\":[{\"id\":\"Ortsgruppe\",\"name\":\"Ortsgruppe\",\"type\":\"character\"},{\"id\":\"Datenquelle\",\"name\":\"Datenquelle\",\"type\":\"character\"}],\"outlined\":true,\"dataKey\":\"bac17b5b11e6f960099471ef5146f5dd\",\"static\":false,\"nested\":true},\"children\":[]}]}]},{\"id\":\"Region\",\"name\":\"Region\",\"type\":\"character\"},{\"id\":\"Anzahl Ortsgruppen\",\"name\":\"Anzahl Ortsgruppen\",\"type\":\"numeric\"}],\"dataKey\":\"58289000cedcb673031a0b49082bb37c\"},\"children\":[]},\"class\":\"reactR_markup\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n### Teilnehmer*innen pro Region\n\n::: {.callout-note collapse=\"true\"}\n## Datenquellen\n\n**Quelle [Ortsgruppen Fragebogen](https://ee-eu.kobotoolbox.org/single/cs5DElJT)**\n\n- **Frage**: \"*In welcher Region liegt deine Ortsgruppe?*\" \n- **Frage**: \"*Teilnehmende:*\"\n\n**Quelle [Teilnehmer*innen Fragebogen](https://ee-eu.kobotoolbox.org/single/UgaA9dLH)**\n\n- **Frage**: \"*Wie heißt deine Ortsgruppe?*\". Diese Information wurde während der Analyse gematcht mit den Regionen. \n\n:::\n\n::: {.cell}\n\n:::\n\n\n\n::: {.panel-tabset}\n\n## Teilnehmer*innen nach Regionen\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"girafe html-widget html-fill-item\" id=\"htmlwidget-b73b0b1e7474f25f7778\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-b73b0b1e7474f25f7778\">{\"x\":{\"html\":\"<?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\"?>\\n<svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' class='ggiraph-svg' role='graphics-document' id='svg_6276496c_8a5f_4956_b9fe_311556199c61' viewBox='0 0 504 360'>\\n <defs id='svg_6276496c_8a5f_4956_b9fe_311556199c61_defs'>\\n  <clipPath id='svg_6276496c_8a5f_4956_b9fe_311556199c61_c1'>\\n   <rect x='0' y='0' width='504' height='360'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_6276496c_8a5f_4956_b9fe_311556199c61_c2'>\\n   <rect x='173.32' y='91.91' width='323.71' height='229.67'/>\\n  <\\/clipPath>\\n <\\/defs>\\n <g id='svg_6276496c_8a5f_4956_b9fe_311556199c61_rootg' class='ggiraph-svg-rootg'>\\n  <g clip-path='url(#svg_6276496c_8a5f_4956_b9fe_311556199c61_c1)'>\\n   <rect x='0' y='0' width='504' height='360' fill='#FFFFFF' fill-opacity='1' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.75' stroke-linejoin='round' stroke-linecap='round' class='ggiraph-svg-bg'/>\\n  <\\/g>\\n  <g clip-path='url(#svg_6276496c_8a5f_4956_b9fe_311556199c61_c2)'>\\n   <polyline points='243.65,321.58 243.65,91.91' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='0.68' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='359.50,321.58 359.50,91.91' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='0.68' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='475.36,321.58 475.36,91.91' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='0.68' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='173.32,308.07 497.03,308.07' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='1.36' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='173.32,285.56 497.03,285.56' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='1.36' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='173.32,263.04 497.03,263.04' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='1.36' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='173.32,240.52 497.03,240.52' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='1.36' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='173.32,218.00 497.03,218.00' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='1.36' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='173.32,195.49 497.03,195.49' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='1.36' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='173.32,172.97 497.03,172.97' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='1.36' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='173.32,150.45 497.03,150.45' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='1.36' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='173.32,127.94 497.03,127.94' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='1.36' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='173.32,105.42 497.03,105.42' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='1.36' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='185.72,321.58 185.72,91.91' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='1.36' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='301.57,321.58 301.57,91.91' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='1.36' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='417.43,321.58 417.43,91.91' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='1.36' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <circle id='svg_6276496c_8a5f_4956_b9fe_311556199c61_e1' cx='239.01' cy='240.52' r='4.27pt' fill='#00BFC4' fill-opacity='1' stroke='#00BFC4' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' title='laut TN-FB: 23 Teilnehmer*innen'/>\\n   <circle id='svg_6276496c_8a5f_4956_b9fe_311556199c61_e2' cx='245.96' cy='172.97' r='4.27pt' fill='#00BFC4' fill-opacity='1' stroke='#00BFC4' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' title='laut TN-FB: 26 Teilnehmer*innen'/>\\n   <circle id='svg_6276496c_8a5f_4956_b9fe_311556199c61_e3' cx='252.91' cy='218' r='4.27pt' fill='#00BFC4' fill-opacity='1' stroke='#00BFC4' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' title='laut TN-FB: 29 Teilnehmer*innen'/>\\n   <circle id='svg_6276496c_8a5f_4956_b9fe_311556199c61_e4' cx='271.45' cy='150.45' r='4.27pt' fill='#00BFC4' fill-opacity='1' stroke='#00BFC4' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' title='laut TN-FB: 37 Teilnehmer*innen'/>\\n   <circle id='svg_6276496c_8a5f_4956_b9fe_311556199c61_e5' cx='222.79' cy='195.49' r='4.27pt' fill='#00BFC4' fill-opacity='1' stroke='#00BFC4' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' title='laut TN-FB: 16 Teilnehmer*innen'/>\\n   <circle id='svg_6276496c_8a5f_4956_b9fe_311556199c61_e6' cx='387.31' cy='105.42' r='4.27pt' fill='#00BFC4' fill-opacity='1' stroke='#00BFC4' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' title='laut TN-FB: 87 Teilnehmer*innen'/>\\n   <circle id='svg_6276496c_8a5f_4956_b9fe_311556199c61_e7' cx='206.57' cy='263.04' r='4.27pt' fill='#00BFC4' fill-opacity='1' stroke='#00BFC4' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' title='laut TN-FB: 9 Teilnehmer*innen'/>\\n   <circle id='svg_6276496c_8a5f_4956_b9fe_311556199c61_e8' cx='188.03' cy='285.56' r='4.27pt' fill='#00BFC4' fill-opacity='1' stroke='#00BFC4' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' title='laut TN-FB: 1 Teilnehmer*innen'/>\\n   <circle id='svg_6276496c_8a5f_4956_b9fe_311556199c61_e9' cx='301.57' cy='127.94' r='4.27pt' fill='#00BFC4' fill-opacity='1' stroke='#00BFC4' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' title='laut TN-FB: 50 Teilnehmer*innen'/>\\n   <circle id='svg_6276496c_8a5f_4956_b9fe_311556199c61_e10' cx='206.57' cy='308.07' r='4.27pt' fill='#00BFC4' fill-opacity='1' stroke='#00BFC4' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' title='laut TN-FB: 9 Teilnehmer*innen'/>\\n   <circle id='svg_6276496c_8a5f_4956_b9fe_311556199c61_e11' cx='278.4' cy='240.52' r='4.27pt' fill='#F8766D' fill-opacity='1' stroke='#F8766D' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' title='laut OG-FB: 40 Teilnehmer*innen'/>\\n   <circle id='svg_6276496c_8a5f_4956_b9fe_311556199c61_e12' cx='278.4' cy='172.97' r='4.27pt' fill='#F8766D' fill-opacity='1' stroke='#F8766D' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' title='laut OG-FB: 40 Teilnehmer*innen'/>\\n   <circle id='svg_6276496c_8a5f_4956_b9fe_311556199c61_e13' cx='266.82' cy='218' r='4.27pt' fill='#F8766D' fill-opacity='1' stroke='#F8766D' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' title='laut OG-FB: 35 Teilnehmer*innen'/>\\n   <circle id='svg_6276496c_8a5f_4956_b9fe_311556199c61_e14' cx='336.33' cy='150.45' r='4.27pt' fill='#F8766D' fill-opacity='1' stroke='#F8766D' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' title='laut OG-FB: 65 Teilnehmer*innen'/>\\n   <circle id='svg_6276496c_8a5f_4956_b9fe_311556199c61_e15' cx='296.94' cy='195.49' r='4.27pt' fill='#F8766D' fill-opacity='1' stroke='#F8766D' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' title='laut OG-FB: 48 Teilnehmer*innen'/>\\n   <circle id='svg_6276496c_8a5f_4956_b9fe_311556199c61_e16' cx='482.31' cy='105.42' r='4.27pt' fill='#F8766D' fill-opacity='1' stroke='#F8766D' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' title='laut OG-FB: 128 Teilnehmer*innen'/>\\n   <circle id='svg_6276496c_8a5f_4956_b9fe_311556199c61_e17' cx='273.77' cy='263.04' r='4.27pt' fill='#F8766D' fill-opacity='1' stroke='#F8766D' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' title='laut OG-FB: 38 Teilnehmer*innen'/>\\n   <circle id='svg_6276496c_8a5f_4956_b9fe_311556199c61_e18' cx='239.01' cy='285.56' r='4.27pt' fill='#F8766D' fill-opacity='1' stroke='#F8766D' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' title='laut OG-FB: 23 Teilnehmer*innen'/>\\n   <circle id='svg_6276496c_8a5f_4956_b9fe_311556199c61_e19' cx='340.97' cy='127.94' r='4.27pt' fill='#F8766D' fill-opacity='1' stroke='#F8766D' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' title='laut OG-FB: 67 Teilnehmer*innen'/>\\n  <\\/g>\\n  <g clip-path='url(#svg_6276496c_8a5f_4956_b9fe_311556199c61_c1)'>\\n   <text x='99.52' y='311.81' font-size='8.4pt' font-family='Atkinson Hyperlegible' fill='#4D4D4D' fill-opacity='1'>keine Angabe<\\/text>\\n   <text x='135.93' y='289.3' font-size='8.4pt' font-family='Atkinson Hyperlegible' fill='#4D4D4D' fill-opacity='1'>Süden<\\/text>\\n   <text x='125.39' y='266.78' font-size='8.4pt' font-family='Atkinson Hyperlegible' fill='#4D4D4D' fill-opacity='1'>Sachsen<\\/text>\\n   <text x='6.97' y='244.26' font-size='8.4pt' font-family='Atkinson Hyperlegible' fill='#4D4D4D' fill-opacity='1'>Bergischland-Ruhrgebiet (BLRG)<\\/text>\\n   <text x='108.89' y='221.75' font-size='8.4pt' font-family='Atkinson Hyperlegible' fill='#4D4D4D' fill-opacity='1'>Niederrhein<\\/text>\\n   <text x='127.38' y='199.23' font-size='8.4pt' font-family='Atkinson Hyperlegible' fill='#4D4D4D' fill-opacity='1'>Ostwerk<\\/text>\\n   <text x='130.61' y='176.71' font-size='8.4pt' font-family='Atkinson Hyperlegible' fill='#4D4D4D' fill-opacity='1'>Hessen<\\/text>\\n   <text x='143.05' y='154.19' font-size='8.4pt' font-family='Atkinson Hyperlegible' fill='#4D4D4D' fill-opacity='1'>Nord<\\/text>\\n   <text x='117.28' y='131.68' font-size='8.4pt' font-family='Atkinson Hyperlegible' fill='#4D4D4D' fill-opacity='1'>Thüringen<\\/text>\\n   <text x='71.62' y='109.16' font-size='8.4pt' font-family='Atkinson Hyperlegible' fill='#4D4D4D' fill-opacity='1'>Ostwestfalen-Lippe<\\/text>\\n   <text x='182.09' y='335.34' font-size='8.4pt' font-family='Atkinson Hyperlegible' fill='#4D4D4D' fill-opacity='1'>0<\\/text>\\n   <text x='294.69' y='335.34' font-size='8.4pt' font-family='Atkinson Hyperlegible' fill='#4D4D4D' fill-opacity='1'>50<\\/text>\\n   <text x='407.93' y='335.34' font-size='8.4pt' font-family='Atkinson Hyperlegible' fill='#4D4D4D' fill-opacity='1'>100<\\/text>\\n   <text x='257.67' y='350.33' font-size='10.5pt' font-family='Atkinson Hyperlegible'>Anzahl Teilnehmer*innen<\\/text>\\n   <text x='234.82' y='67.02' font-size='10.5pt' font-family='Atkinson Hyperlegible'>Datenquelle<\\/text>\\n   <circle cx='324.29' cy='62.35' r='4.27pt' fill='#F8766D' fill-opacity='1' stroke='#F8766D' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round'/>\\n   <circle cx='388.78' cy='62.35' r='4.27pt' fill='#00BFC4' fill-opacity='1' stroke='#00BFC4' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round'/>\\n   <text x='339.91' y='66.09' font-size='8.4pt' font-family='Atkinson Hyperlegible'>OG-FB<\\/text>\\n   <text x='404.39' y='66.09' font-size='8.4pt' font-family='Atkinson Hyperlegible'>TN-FB<\\/text>\\n   <text x='6.97' y='37.07' font-size='10.5pt' font-family='Atkinson Hyperlegible'>beide Fragebögen<\\/text>\\n   <text x='6.97' y='17.67' font-size='12pt' font-weight='bold' font-family='Atkinson Hyperlegible'>Anzahl Teilnehmer*innen<\\/text>\\n  <\\/g>\\n <\\/g>\\n<\\/svg>\",\"js\":null,\"uid\":\"svg_6276496c_8a5f_4956_b9fe_311556199c61\",\"ratio\":1.4,\"settings\":{\"tooltip\":{\"css\":\".tooltip_SVGID_ { padding:5px;background:black;color:white;border-radius:2px;text-align:left; ; position:absolute;pointer-events:none;z-index:999;}\",\"placement\":\"doc\",\"opacity\":0.9,\"offx\":10,\"offy\":10,\"use_cursor_pos\":true,\"use_fill\":false,\"use_stroke\":false,\"delay_over\":200,\"delay_out\":500},\"hover\":{\"css\":\".hover_data_SVGID_ { fill:orange;stroke:black;cursor:pointer; }\\ntext.hover_data_SVGID_ { stroke:none;fill:orange; }\\ncircle.hover_data_SVGID_ { fill:orange;stroke:black; }\\nline.hover_data_SVGID_, polyline.hover_data_SVGID_ { fill:none;stroke:orange; }\\nrect.hover_data_SVGID_, polygon.hover_data_SVGID_, path.hover_data_SVGID_ { fill:orange;stroke:none; }\\nimage.hover_data_SVGID_ { stroke:orange; }\",\"reactive\":true,\"nearest_distance\":null},\"hover_inv\":{\"css\":\"\"},\"hover_key\":{\"css\":\".hover_key_SVGID_ { fill:orange;stroke:black;cursor:pointer; }\\ntext.hover_key_SVGID_ { stroke:none;fill:orange; }\\ncircle.hover_key_SVGID_ { fill:orange;stroke:black; }\\nline.hover_key_SVGID_, polyline.hover_key_SVGID_ { fill:none;stroke:orange; }\\nrect.hover_key_SVGID_, polygon.hover_key_SVGID_, path.hover_key_SVGID_ { fill:orange;stroke:none; }\\nimage.hover_key_SVGID_ { stroke:orange; }\",\"reactive\":true},\"hover_theme\":{\"css\":\".hover_theme_SVGID_ { fill:orange;stroke:black;cursor:pointer; }\\ntext.hover_theme_SVGID_ { stroke:none;fill:orange; }\\ncircle.hover_theme_SVGID_ { fill:orange;stroke:black; }\\nline.hover_theme_SVGID_, polyline.hover_theme_SVGID_ { fill:none;stroke:orange; }\\nrect.hover_theme_SVGID_, polygon.hover_theme_SVGID_, path.hover_theme_SVGID_ { fill:orange;stroke:none; }\\nimage.hover_theme_SVGID_ { stroke:orange; }\",\"reactive\":true},\"select\":{\"css\":\".select_data_SVGID_ { fill:red;stroke:black;cursor:pointer; }\\ntext.select_data_SVGID_ { stroke:none;fill:red; }\\ncircle.select_data_SVGID_ { fill:red;stroke:black; }\\nline.select_data_SVGID_, polyline.select_data_SVGID_ { fill:none;stroke:red; }\\nrect.select_data_SVGID_, polygon.select_data_SVGID_, path.select_data_SVGID_ { fill:red;stroke:none; }\\nimage.select_data_SVGID_ { stroke:red; }\",\"type\":\"multiple\",\"only_shiny\":true,\"selected\":[]},\"select_inv\":{\"css\":\"\"},\"select_key\":{\"css\":\".select_key_SVGID_ { fill:red;stroke:black;cursor:pointer; }\\ntext.select_key_SVGID_ { stroke:none;fill:red; }\\ncircle.select_key_SVGID_ { fill:red;stroke:black; }\\nline.select_key_SVGID_, polyline.select_key_SVGID_ { fill:none;stroke:red; }\\nrect.select_key_SVGID_, polygon.select_key_SVGID_, path.select_key_SVGID_ { fill:red;stroke:none; }\\nimage.select_key_SVGID_ { stroke:red; }\",\"type\":\"single\",\"only_shiny\":true,\"selected\":[]},\"select_theme\":{\"css\":\".select_theme_SVGID_ { fill:red;stroke:black;cursor:pointer; }\\ntext.select_theme_SVGID_ { stroke:none;fill:red; }\\ncircle.select_theme_SVGID_ { fill:red;stroke:black; }\\nline.select_theme_SVGID_, polyline.select_theme_SVGID_ { fill:none;stroke:red; }\\nrect.select_theme_SVGID_, polygon.select_theme_SVGID_, path.select_theme_SVGID_ { fill:red;stroke:none; }\\nimage.select_theme_SVGID_ { stroke:red; }\",\"type\":\"single\",\"only_shiny\":true,\"selected\":[]},\"zoom\":{\"min\":1,\"max\":1,\"duration\":300},\"toolbar\":{\"position\":\"topright\",\"pngname\":\"diagram\",\"tooltips\":null,\"fixed\":false,\"hidden\":[],\"delay_over\":200,\"delay_out\":500},\"sizing\":{\"rescale\":true,\"width\":1}}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n## Alternative Darstellung\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"girafe html-widget html-fill-item\" id=\"htmlwidget-3400d7ac96c48bb05169\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-3400d7ac96c48bb05169\">{\"x\":{\"html\":\"<?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\"?>\\n<svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' class='ggiraph-svg' role='graphics-document' id='svg_b4fab092_98e1_49f7_b57a_98778806493e' viewBox='0 0 504 360'>\\n <defs id='svg_b4fab092_98e1_49f7_b57a_98778806493e_defs'>\\n  <clipPath id='svg_b4fab092_98e1_49f7_b57a_98778806493e_c1'>\\n   <rect x='0' y='0' width='504' height='360'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_b4fab092_98e1_49f7_b57a_98778806493e_c2'>\\n   <rect x='173.32' y='46.73' width='323.71' height='274.85'/>\\n  <\\/clipPath>\\n <\\/defs>\\n <g id='svg_b4fab092_98e1_49f7_b57a_98778806493e_rootg' class='ggiraph-svg-rootg'>\\n  <g clip-path='url(#svg_b4fab092_98e1_49f7_b57a_98778806493e_c1)'>\\n   <rect x='0' y='0' width='504' height='360' fill='#FFFFFF' fill-opacity='1' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.75' stroke-linejoin='round' stroke-linecap='round' class='ggiraph-svg-bg'/>\\n  <\\/g>\\n  <g clip-path='url(#svg_b4fab092_98e1_49f7_b57a_98778806493e_c2)'>\\n   <polyline points='173.32,-341.29 497.03,-341.29' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='0.68' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='173.32,-1688.59 497.03,-1688.59' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='0.68' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='173.32,-3035.90 497.03,-3035.90' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='0.68' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='188.03,321.58 188.03,46.73' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='1.36' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='190.35,321.58 190.35,46.73' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='1.36' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='192.67,321.58 192.67,46.73' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='1.36' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='194.99,321.58 194.99,46.73' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='1.36' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='197.30,321.58 197.30,46.73' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='1.36' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='199.62,321.58 199.62,46.73' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='1.36' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='201.94,321.58 201.94,46.73' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='1.36' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='204.25,321.58 204.25,46.73' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='1.36' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='206.57,321.58 206.57,46.73' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='1.36' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='208.89,321.58 208.89,46.73' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='1.36' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='173.32,332.36 497.03,332.36' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='1.36' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='173.32,-1014.94 497.03,-1014.94' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='1.36' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='173.32,-2362.25 497.03,-2362.25' fill='none' stroke='#EBEBEB' stroke-opacity='1' stroke-width='1.36' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <line id='svg_b4fab092_98e1_49f7_b57a_98778806493e_e1' x1='239.01' y1='305.42' x2='278.4' y2='305.42' stroke='#000000' stroke-opacity='1' stroke-width='4.27' stroke-linejoin='round' stroke-linecap='butt' title='Bergischland-Ruhrgebiet (BLRG): Zwischen 23 und 40 Teilnehmer*innen'/>\\n   <line id='svg_b4fab092_98e1_49f7_b57a_98778806493e_e2' x1='245.96' y1='278.47' x2='278.4' y2='278.47' stroke='#000000' stroke-opacity='1' stroke-width='4.27' stroke-linejoin='round' stroke-linecap='butt' title='Hessen: Zwischen 26 und 40 Teilnehmer*innen'/>\\n   <line id='svg_b4fab092_98e1_49f7_b57a_98778806493e_e3' x1='252.91' y1='224.58' x2='266.82' y2='224.58' stroke='#000000' stroke-opacity='1' stroke-width='4.27' stroke-linejoin='round' stroke-linecap='butt' title='Niederrhein: Zwischen 29 und 35 Teilnehmer*innen'/>\\n   <line id='svg_b4fab092_98e1_49f7_b57a_98778806493e_e4' x1='271.45' y1='197.63' x2='336.33' y2='197.63' stroke='#000000' stroke-opacity='1' stroke-width='4.27' stroke-linejoin='round' stroke-linecap='butt' title='Nord: Zwischen 37 und 65 Teilnehmer*innen'/>\\n   <line id='svg_b4fab092_98e1_49f7_b57a_98778806493e_e5' x1='222.79' y1='170.69' x2='296.94' y2='170.69' stroke='#000000' stroke-opacity='1' stroke-width='4.27' stroke-linejoin='round' stroke-linecap='butt' title='Ostwerk: Zwischen 16 und 48 Teilnehmer*innen'/>\\n   <line id='svg_b4fab092_98e1_49f7_b57a_98778806493e_e6' x1='387.31' y1='143.74' x2='482.31' y2='143.74' stroke='#000000' stroke-opacity='1' stroke-width='4.27' stroke-linejoin='round' stroke-linecap='butt' title='Ostwestfalen-Lippe: Zwischen 87 und 128 Teilnehmer*innen'/>\\n   <line id='svg_b4fab092_98e1_49f7_b57a_98778806493e_e7' x1='206.57' y1='116.79' x2='273.77' y2='116.79' stroke='#000000' stroke-opacity='1' stroke-width='4.27' stroke-linejoin='round' stroke-linecap='butt' title='Sachsen: Zwischen 9 und 38 Teilnehmer*innen'/>\\n   <line id='svg_b4fab092_98e1_49f7_b57a_98778806493e_e8' x1='188.03' y1='89.85' x2='239.01' y2='89.85' stroke='#000000' stroke-opacity='1' stroke-width='4.27' stroke-linejoin='round' stroke-linecap='butt' title='Süden: Zwischen 1 und 23 Teilnehmer*innen'/>\\n   <line id='svg_b4fab092_98e1_49f7_b57a_98778806493e_e9' x1='301.57' y1='62.9' x2='340.97' y2='62.9' stroke='#000000' stroke-opacity='1' stroke-width='4.27' stroke-linejoin='round' stroke-linecap='butt' title='Thüringen: Zwischen 50 und 67 Teilnehmer*innen'/>\\n  <\\/g>\\n  <g clip-path='url(#svg_b4fab092_98e1_49f7_b57a_98778806493e_c1)'>\\n   <text x='6.97' y='309.16' font-size='8.4pt' font-family='Atkinson Hyperlegible' fill='#4D4D4D' fill-opacity='1'>Bergischland-Ruhrgebiet (BLRG)<\\/text>\\n   <text x='130.61' y='282.21' font-size='8.4pt' font-family='Atkinson Hyperlegible' fill='#4D4D4D' fill-opacity='1'>Hessen<\\/text>\\n   <text x='99.52' y='255.26' font-size='8.4pt' font-family='Atkinson Hyperlegible' fill='#4D4D4D' fill-opacity='1'>keine Angabe<\\/text>\\n   <text x='108.89' y='228.32' font-size='8.4pt' font-family='Atkinson Hyperlegible' fill='#4D4D4D' fill-opacity='1'>Niederrhein<\\/text>\\n   <text x='143.05' y='201.37' font-size='8.4pt' font-family='Atkinson Hyperlegible' fill='#4D4D4D' fill-opacity='1'>Nord<\\/text>\\n   <text x='127.38' y='174.43' font-size='8.4pt' font-family='Atkinson Hyperlegible' fill='#4D4D4D' fill-opacity='1'>Ostwerk<\\/text>\\n   <text x='71.62' y='147.48' font-size='8.4pt' font-family='Atkinson Hyperlegible' fill='#4D4D4D' fill-opacity='1'>Ostwestfalen-Lippe<\\/text>\\n   <text x='125.39' y='120.53' font-size='8.4pt' font-family='Atkinson Hyperlegible' fill='#4D4D4D' fill-opacity='1'>Sachsen<\\/text>\\n   <text x='135.93' y='93.59' font-size='8.4pt' font-family='Atkinson Hyperlegible' fill='#4D4D4D' fill-opacity='1'>Süden<\\/text>\\n   <text x='117.28' y='66.64' font-size='8.4pt' font-family='Atkinson Hyperlegible' fill='#4D4D4D' fill-opacity='1'>Thüringen<\\/text>\\n   <text x='182.09' y='335.34' font-size='8.4pt' font-family='Atkinson Hyperlegible' fill='#4D4D4D' fill-opacity='1'>0<\\/text>\\n   <text x='294.69' y='335.34' font-size='8.4pt' font-family='Atkinson Hyperlegible' fill='#4D4D4D' fill-opacity='1'>50<\\/text>\\n   <text x='407.93' y='335.34' font-size='8.4pt' font-family='Atkinson Hyperlegible' fill='#4D4D4D' fill-opacity='1'>100<\\/text>\\n   <text x='257.67' y='350.33' font-size='10.5pt' font-family='Atkinson Hyperlegible'>Anzahl Teilnehmer*innen<\\/text>\\n   <text x='6.97' y='37.07' font-size='10.5pt' font-family='Atkinson Hyperlegible'>beide Fragebögen<\\/text>\\n   <text x='6.97' y='17.67' font-size='12pt' font-weight='bold' font-family='Atkinson Hyperlegible'>Anzahl Teilnehmer*innen nach Region<\\/text>\\n  <\\/g>\\n <\\/g>\\n<\\/svg>\",\"js\":null,\"uid\":\"svg_b4fab092_98e1_49f7_b57a_98778806493e\",\"ratio\":1.4,\"settings\":{\"tooltip\":{\"css\":\".tooltip_SVGID_ { padding:5px;background:black;color:white;border-radius:2px;text-align:left; ; position:absolute;pointer-events:none;z-index:999;}\",\"placement\":\"doc\",\"opacity\":0.9,\"offx\":10,\"offy\":10,\"use_cursor_pos\":true,\"use_fill\":false,\"use_stroke\":false,\"delay_over\":200,\"delay_out\":500},\"hover\":{\"css\":\".hover_data_SVGID_ { fill:orange;stroke:black;cursor:pointer; }\\ntext.hover_data_SVGID_ { stroke:none;fill:orange; }\\ncircle.hover_data_SVGID_ { fill:orange;stroke:black; }\\nline.hover_data_SVGID_, polyline.hover_data_SVGID_ { fill:none;stroke:orange; }\\nrect.hover_data_SVGID_, polygon.hover_data_SVGID_, path.hover_data_SVGID_ { fill:orange;stroke:none; }\\nimage.hover_data_SVGID_ { stroke:orange; }\",\"reactive\":true,\"nearest_distance\":null},\"hover_inv\":{\"css\":\"\"},\"hover_key\":{\"css\":\".hover_key_SVGID_ { fill:orange;stroke:black;cursor:pointer; }\\ntext.hover_key_SVGID_ { stroke:none;fill:orange; }\\ncircle.hover_key_SVGID_ { fill:orange;stroke:black; }\\nline.hover_key_SVGID_, polyline.hover_key_SVGID_ { fill:none;stroke:orange; }\\nrect.hover_key_SVGID_, polygon.hover_key_SVGID_, path.hover_key_SVGID_ { fill:orange;stroke:none; }\\nimage.hover_key_SVGID_ { stroke:orange; }\",\"reactive\":true},\"hover_theme\":{\"css\":\".hover_theme_SVGID_ { fill:orange;stroke:black;cursor:pointer; }\\ntext.hover_theme_SVGID_ { stroke:none;fill:orange; }\\ncircle.hover_theme_SVGID_ { fill:orange;stroke:black; }\\nline.hover_theme_SVGID_, polyline.hover_theme_SVGID_ { fill:none;stroke:orange; }\\nrect.hover_theme_SVGID_, polygon.hover_theme_SVGID_, path.hover_theme_SVGID_ { fill:orange;stroke:none; }\\nimage.hover_theme_SVGID_ { stroke:orange; }\",\"reactive\":true},\"select\":{\"css\":\".select_data_SVGID_ { fill:red;stroke:black;cursor:pointer; }\\ntext.select_data_SVGID_ { stroke:none;fill:red; }\\ncircle.select_data_SVGID_ { fill:red;stroke:black; }\\nline.select_data_SVGID_, polyline.select_data_SVGID_ { fill:none;stroke:red; }\\nrect.select_data_SVGID_, polygon.select_data_SVGID_, path.select_data_SVGID_ { fill:red;stroke:none; }\\nimage.select_data_SVGID_ { stroke:red; }\",\"type\":\"multiple\",\"only_shiny\":true,\"selected\":[]},\"select_inv\":{\"css\":\"\"},\"select_key\":{\"css\":\".select_key_SVGID_ { fill:red;stroke:black;cursor:pointer; }\\ntext.select_key_SVGID_ { stroke:none;fill:red; }\\ncircle.select_key_SVGID_ { fill:red;stroke:black; }\\nline.select_key_SVGID_, polyline.select_key_SVGID_ { fill:none;stroke:red; }\\nrect.select_key_SVGID_, polygon.select_key_SVGID_, path.select_key_SVGID_ { fill:red;stroke:none; }\\nimage.select_key_SVGID_ { stroke:red; }\",\"type\":\"single\",\"only_shiny\":true,\"selected\":[]},\"select_theme\":{\"css\":\".select_theme_SVGID_ { fill:red;stroke:black;cursor:pointer; }\\ntext.select_theme_SVGID_ { stroke:none;fill:red; }\\ncircle.select_theme_SVGID_ { fill:red;stroke:black; }\\nline.select_theme_SVGID_, polyline.select_theme_SVGID_ { fill:none;stroke:red; }\\nrect.select_theme_SVGID_, polygon.select_theme_SVGID_, path.select_theme_SVGID_ { fill:red;stroke:none; }\\nimage.select_theme_SVGID_ { stroke:red; }\",\"type\":\"single\",\"only_shiny\":true,\"selected\":[]},\"zoom\":{\"min\":1,\"max\":1,\"duration\":300},\"toolbar\":{\"position\":\"topright\",\"pngname\":\"diagram\",\"tooltips\":null,\"fixed\":false,\"hidden\":[],\"delay_over\":200,\"delay_out\":500},\"sizing\":{\"rescale\":true,\"width\":1}}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n:::\n\n\n## Geschlecht und Alter nach Regionen \n\n**TODO** \n",
    "supporting": [
      "deskriptiv_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/core-js-2.5.3/shim.min.js\"></script>\n<script src=\"site_libs/react-18.2.0/react.min.js\"></script>\n<script src=\"site_libs/react-18.2.0/react-dom.min.js\"></script>\n<script src=\"site_libs/reactwidget-2.0.0/react-tools.js\"></script>\n<link href=\"site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<link href=\"site_libs/reactable-0.4.4/reactable.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/reactable-binding-0.4.4/reactable.js\"></script>\n<script src=\"site_libs/d3-bundle-5.16.0/d3-bundle.min.js\"></script>\n<script src=\"site_libs/d3-lasso-0.0.5/d3-lasso.min.js\"></script>\n<script src=\"site_libs/save-svg-as-png-1.4.17/save-svg-as-png.min.js\"></script>\n<script src=\"site_libs/flatbush-4.4.0/flatbush.min.js\"></script>\n<link href=\"site_libs/ggiraphjs-0.8.10/ggiraphjs.min.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/ggiraphjs-0.8.10/ggiraphjs.min.js\"></script>\n<script src=\"site_libs/girafe-binding-0.8.12/girafe.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}