library(tidyverse)
library(ggiraph)
library(wordcloud2)
library(patchwork)
library(here)
library(stringr)
library(scales)
library(ggplot2)
library(reactable)
library(knitr)
library(htmltools)
library(glue)
library(dplyr)

source(here::here("config/viz_config.R"))
source(here::here("R/quarto-utils.R"))
source(here::here("R/utils.R"))
source(here::here("R/viz.R"))
 
options(OutDec = ",")
